<a href="https://colab.research.google.com/github/mujtaba098/ML_CAT_1/blob/master/CAT_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a comprehensive Notebook i.e. both code and notes demonstrating:

i. Data preprocessing: Filling Missing values (Justify your group strategy on this),
Encoding, Feature Selection, Feature Extraction (Truncated SVD or PCA 90% and
above variance) (20 marks)

ii. Data Distributions Examination: Using Seaborn Library do a pair plot of all
attributes to the target and describe the distributions (2 marks)

iii. Model Selection: This is a Regression problem aimed at building a model to
predict House Prices in California State, demonstrate model selection amongst
many of the Regression models (10 marks)

iv. Hyperparameter Tuning (Randomized): Demonstrate Tuning of hyperparameters
in the models above with Data Splitting (5 marks)

v. Cross Validation: Demonstrate K-Fold Cross Validation. What happens to accuracy
when you increase value of K? Explain this effect. (5 marks)

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import pandas.util.testing as tm
from sklearn import svm
from sklearn.decomposition import PCA
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LassoCV
from sklearn import linear_model
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.svm import SVR
from sklearn.model_selection import cross_val_score


**i) Data Preprocessing**

In [ ]:
#loading the data
data = fetch_california_housing()
new_data = pd.DataFrame(data.data, columns=data.feature_names)
#information about the dataset
print(data['DESCR'])
data

**v. cross validation** K-fold

In [ ]:
K = 4
kf = KFold(n_splits = K, shuffle = True)
for train, test in kf.split(data):
  print ("%s %s" % (train, test))

[0 1 2] [3]
[0 2 3] [1]
[0 1 3] [2]
[1 2 3] [0]


Increasing the value of K reduces the accuracy

In [ ]:
df.head()


MedInc  HouseAge  AveRooms  ...  AveOccup  Latitude  Longitude
0  8.3252      41.0  6.984127  ...  2.555556     37.88    -122.23
1  8.3014      21.0  6.238137  ...  2.109842     37.86    -122.22
2  7.2574      52.0  8.288136  ...  2.802260     37.85    -122.24
3  5.6431      52.0  5.817352  ...  2.547945     37.85    -122.25
4  3.8462      52.0  6.281853  ...  2.181467     37.85    -122.25

[5 rows x 8 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB


Each column has 20640/20640 values, thus suggesting the absence of null values


In the case of missing values, we mark missing values as NaN.

Values with a NaN value are ignored from operations like sum, count, etc.

We can mark values as NaN easily with the Pandas DataFrame by using the replace() function on a subset of the columns we are interested in.


No encoding because the dataset consists of floats

**Feature Selection**

In [ ]:
column_names=data.feature_names
target=data.target
categorical_data=new_data
numerical=['MedInc','HouseAge','AveRooms','AveBedrms','Population','AveOccup']

for feature in column_names:
  categorical_data[feature]=categorical_data[feature].astype('category')

for feature in numerical:
  categorical_data[feature]= categorical_data[feature].cat.codes

categorical_data

MedInc  HouseAge  AveRooms  ...  AveOccup  Latitude  Longitude
0       12416        40     17422  ...      6200     37.88    -122.23
1       12411        20     15292  ...      2171     37.86    -122.22
2       11941        51     18851  ...      9150     37.85    -122.24
3       10269        51     13297  ...      6102     37.85    -122.25
4        6656        51     15461  ...      2620     37.85    -122.25
...       ...       ...       ...  ...       ...       ...        ...
20635     740        24      8473  ...      6253     39.48    -121.09
20636    3179        17     14726  ...     12675     39.49    -121.21
20637    1037        16      9514  ...      3757     39.43    -121.22
20638    1405        17     10299  ...      2249     39.43    -121.32
20639    2752        15      9811  ...      6924     39.37    -121.24

[20640 rows x 8 columns]

In [ ]:
categorical_data.drop('Latitude',axis=1,inplace=True)
categorical_data.drop('Longitude',axis=1,inplace=True)

Combining the categorical data with target

In [ ]:
data_copy=categorical_data.copy()

#Generating dataframe from target array
dataset = pd.DataFrame({'Target':data.target})
dataset


temp_data = pd.concat([data_copy,dataset],axis=1)
temp_data

Slice our data

In [ ]:
all_features = list(data_copy.columns)
X = data_copy.loc[:,all_features].values
y = temp_data.loc[:,['Target']].values
y

array([[4.526],
       [3.585],
       [3.521],
       ...,
       [0.923],
       [0.847],
       [0.894]])

X is standardized

In [ ]:
X = StandardScaler().fit_transform(X)
X

Calculate Principal Components

In [ ]:
#Principle components
pca=PCA(n_components=5)
pc_s=pca.fit_transform(X)
#Returning Principle Components
pca_data=pd.DataFrame(pc_s,columns=['PC1','PC2','PC3','PC4','PC5'])
final_data = pd.concat([pca_data,dataset],axis=1)
final_data

variance

In [ ]:
arr=pca.explained_variance_ratio_

calculate the total variance

In [ ]:
sum =0
for i in range(0, len(arr)):    
   sum = sum + arr[i];
Variance=sum*100


print('PCA variance is '+str(Variance) +'%')

**ii) Using Seaborn Library**
to pair a plot of all the attributes to the Target

Plot of median income and Target

In [ ]:
plot_data=pd.DataFrame(data.data, columns=data.feature_names)
target_data=pd.DataFrame({'Target':data.target})
data_MedInc=pd.concat([plot_data['MedInc'],target_data],axis=1)
data_MedInc
sns.pairplot(data_MedInc,kind='reg',diag_kind='kde')

Plot of HouseAge and Target

In [ ]:
data_plot=pd.concat([plot_data['HouseAge'],target_data],axis=1)
data_plot
sns.pairplot(data_plot,kind='reg',diag_kind='kde')

Plot of Avg Rooms and Target

In [ ]:
data_plot=pd.concat([plot_data['AveRooms'],target_data],axis=1)
data_plot
sns.pairplot(data_plot,kind='reg',diag_kind='kde')

Plot for Average Bedrooms and Target

In [ ]:
data_plot=pd.concat([plot_data['AveBedrms'],target_data],axis=1)
data_plot
sns.pairplot(data_plot,kind='reg',diag_kind='kde')

Plot of Population and Target

In [ ]:
data_plot=pd.concat([plot_data['Population'],target_data],axis=1)
data_plot
sns.pairplot(data_plot,kind='reg',diag_kind='kde')

Plot of Average Occupancy and Target

In [ ]:
data_plot=pd.concat([plot_data['AveOccup'],target_data],axis=1)
data_plot
sns.pairplot(data_plot,kind='reg',diag_kind='kde')

**iii) Model Selection and iv) Hyperparameter Tuning**

Linear regression will be used to predict the target value

In [ ]:
Usage of Multiple Linear Regression

**Data Splitting** X and y into training and testing sets using train_set_split from sklearn

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y.ravel(), test_size=0.33, random_state=0) 

Use Linear Regression object from sklearn to Calculate

In [ ]:
reg = linear_model.LinearRegression()


Train the model using the training sets

In [ ]:
reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

Regression Coefficients

In [ ]:
reg.coef_

Regression Score

In [ ]:
Y_pred = reg.predict(X_test)
reg.score(X_train,y_train)

In [ ]:
plt.style.use('fivethirtyeight') 
plt.scatter(reg.predict(X_train), reg.predict(X_train) - y_train, color = "red", s = 20, label = 'Train data') #Error in train data
plt.scatter(reg.predict(X_test), reg.predict(X_test) - y_test, color = "yellow", s = 10, label = 'Test data') #Error in Test data
plt.hlines(y = 0, xmin = 0, xmax = 5, linewidth = 2) #Residual Error Line
plt.legend(loc = 'upper right') 
plt.title("Errors") 
plt.show() 